version = 0.1

[default.deploy.parameters]
stack_name = "manas-rai-portfolio"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
resolve_image_repos = true
resolve_s3 = true
confirm_changeset = true
